--From the table STUDENT_INFO and RESULT perform the following queries:

SELECT * FROM STUDENT_INFO
SELECT * FROM RESULT

--Part –> A

--1. Combine information from Student and Result table using cross join (Cartesian product).

SELECT *
FROM STUDENT_INFO, RESULT

--2. Perform inner join on Student and Result tables.

SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH,RESULT.RNO,RESULT.RESULTID,RESULT.SPI
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO

--3. Perform the left outer join on Student and Result tables.

SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH,RESULT.RNO,RESULT.RESULTID,RESULT.SPI
FROM STUDENT_INFO LEFT OUTER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO

--4. Perform the right outer join on Student and Result tables.

SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH,RESULT.RNO,RESULT.RESULTID,RESULT.SPI
FROM STUDENT_INFO RIGHT OUTER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO

--5. Perform the full outer join on Student and Result tables.

SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH,RESULT.RNO,RESULT.RESULTID,RESULT.SPI
FROM STUDENT_INFO FULL OUTER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO

--6. Display Rno, Name, Branch and SPI of all students.

SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH,RESULT.SPI
FROM STUDENT_INFO LEFT OUTER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO

--7. Display Rno, Name, Branch and SPI of CE branch students only.

SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH,RESULT.SPI
FROM STUDENT_INFO LEFT OUTER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
WHERE STUDENT_INFO.BRANCH = 'CE'

--8. Display Rno, Name, Branch and SPI of students other than EC branch.

SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH,RESULT.SPI
FROM STUDENT_INFO LEFT OUTER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
WHERE STUDENT_INFO.BRANCH != 'EC'

--9. Display Rno, Name and SPI of students whose SPI is greater than 8.


SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH,RESULT.SPI
FROM STUDENT_INFO LEFT OUTER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
WHERE RESULT.SPI > 8

--10. Display Rno, Name and Branch of students whose SPI is less than 8.

SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH
FROM STUDENT_INFO LEFT OUTER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
WHERE RESULT.SPI < 8

--11. Display average result of each branch.

SELECT STUDENT_INFO.BRANCH, AVG(RESULT.SPI)
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
GROUP BY STUDENT_INFO.BRANCH

--12. Display average result of CE and ME branch.

SELECT STUDENT_INFO.BRANCH, AVG(RESULT.SPI)
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
WHERE BRANCH IN ('CE','ME')
GROUP BY BRANCH

--13. Display maximum and minimum SPI of each branch.

SELECT STUDENT_INFO.BRANCH,MAX(RESULT.SPI) AS MAXIMUM_SPI,MIN(RESULT.SPI) MINIMUM_SPI
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
GROUP BY BRANCH

--14. Display branch-wise student count in descending order.

SELECT STUDENT_INFO.BRANCH,COUNT(RESULT.RNO) AS COUNT_OF_STUDENT
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
GROUP BY BRANCH
ORDER BY COUNT(RESULT.RNO) DESC

--15. Display branch-wise total SPI of students.

SELECT STUDENT_INFO.BRANCH,SUM(RESULT.SPI) AS TOTAL_SPI
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
GROUP BY BRANCH


--Part –> B

--16. Display branch-wise number of students having SPI greater than 8.

SELECT STUDENT_INFO.BRANCH,COUNT(RESULT.SPI) AS COUNT_STUDENTS
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
WHERE RESULT.SPI > 8
GROUP BY BRANCH

--17. Display branch-wise number of students having SPI less than 8.

SELECT STUDENT_INFO.BRANCH,COUNT(RESULT.SPI) AS COUNT_STUDENTS
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
WHERE RESULT.SPI < 8
GROUP BY BRANCH

--18. Display branch-wise average SPI greater than 7.

SELECT STUDENT_INFO.BRANCH,AVG(RESULT.SPI) AS AVERAGE_SPI
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
WHERE RESULT.SPI > 7
GROUP BY BRANCH

--19. Display branches having more than 1 students.

SELECT STUDENT_INFO.BRANCH,COUNT(RESULT.RNO) AS COUNT_STUDENTS
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
GROUP BY BRANCH
HAVING COUNT(RESULT.RNO) > 1

--20. Display branches where maximum SPI is greater than 9.

SELECT STUDENT_INFO.BRANCH,MAX(RESULT.SPI) AS MAXIMUM_SPI
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
WHERE RESULT.SPI > 9
GROUP BY BRANCH


--Part –> C

--21. Display average result of each branch and sort them in ascending order by SPI.

SELECT STUDENT_INFO.BRANCH,AVG(RESULT.SPI) AS AVERAGE_SPI
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
GROUP BY BRANCH
ORDER BY AVG(RESULT.SPI) 

--22. Display highest SPI from each branch and sort them in descending order.

SELECT STUDENT_INFO.BRANCH,MAX(RESULT.SPI) AS HIGHEST_SPI
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
GROUP BY BRANCH
ORDER BY MAX(RESULT.SPI) DESC 

--23. Display average result of each branch and sort them in ascending order by SPI.

SELECT STUDENT_INFO.BRANCH,AVG(RESULT.SPI) AS AVERAGE_SPI
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
GROUP BY BRANCH
ORDER BY AVG(RESULT.SPI)

--24. Display highest SPI from each branch and sort them in descending order.

SELECT STUDENT_INFO.BRANCH,MAX(RESULT.SPI) AS HIGHEST_SPI
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
GROUP BY BRANCH
ORDER BY MAX(RESULT.SPI) DESC 

--25. Display branches where difference between max and min SPI is greater than 1.

SELECT STUDENT_INFO.BRANCH,MAX(RESULT.SPI)-MIN(RESULT.SPI) AS DIFFRENCE
FROM STUDENT_INFO INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO
GROUP BY BRANCH
HAVING MAX(RESULT.SPI)-MIN(RESULT.SPI) > 1