--From the table STADIUM, TEAM and PLAYER perform the following queries:

SELECT * FROM STADIUM
SELECT * FROM TEAM
SELECT * FROM PLAYER

--Part –> A

--1. Display players who belong to teams located in ‘Mumbai’.

SELECT PLAYER_FIRST_NAME AS PLAYERS
FROM PLAYER 
INNER JOIN TEAM
ON PLAYER.TEAM_ID = TEAM.TEAM_ID
INNER JOIN STADIUM
ON STADIUM.STADIUM_ID = TEAM.HOME_STADIUM_ID
WHERE STADIUM_CITY = 'MUMBAI'

--2. Display all teams and players.

SELECT TEAM_NAME, PLAYER_FIRST_NAME,PLAYER_LAST_NAME
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID

--3. Display players along with team wins and stadium city.

SELECT PLAYER_FIRST_NAME AS PLAYERS,TEAM_WINS AS TEAM_WINS, STADIUM_CITY AS CITY
FROM PLAYER 
INNER JOIN TEAM
ON PLAYER.TEAM_ID = TEAM.TEAM_ID
INNER JOIN STADIUM
ON STADIUM.STADIUM_ID = TEAM.HOME_STADIUM_ID

--4. Display team name and number of players in each team.

SELECT TEAM_NAME AS TEAM_NAME, COUNT(PLAYER_ID) AS NO_OF_PLAYERS
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
GROUP BY TEAM_NAME

--5. Display team name, coach, and number of bowlers in each team.

SELECT TEAM_NAME AS TEAM, TEAM_COACH AS COACH, COUNT(PLAYER_ROLE) AS NO_OF_BOWLERS
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
WHERE PLAYER_ROLE = 'BOWLER'
GROUP BY TEAM_NAME,TEAM_COACH

--6. Display team name with count of batsmen, bowlers, and all-rounders.

SELECT TEAM_NAME, COUNT(PLAYER_ROLE) AS BATSMAN
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
WHERE PLAYER_ROLE = 'BATSMAN'
GROUP BY TEAM_NAME

SELECT TEAM_NAME, COUNT(PLAYER_ROLE) AS BOWLERS
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
WHERE PLAYER_ROLE = 'BOWLER'
GROUP BY TEAM_NAME

SELECT TEAM_NAME, COUNT(PLAYER_ROLE) AS ALL_ROUNDER
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
WHERE PLAYER_ROLE = 'ALL-ROUNDER'
GROUP BY TEAM_NAME

--7. Display stadiums where teams have won more than 10 matches.

SELECT STADIUM_NAME,TEAM_WINS 
FROM STADIUM 
INNER JOIN TEAM
ON STADIUM.STADIUM_ID = TEAM.HOME_STADIUM_ID
WHERE TEAM_WINS > 10 

--8. Display team name and number of players whose matches played is greater than 25.

SELECT TEAM_NAME, COUNT(PLAYER_ID) AS NO_PLAYERS
FROM TEAM 
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
WHERE PLAYER_MATCHES_PLAYED > 25
GROUP BY TEAM_NAME

--9. Display team name and total number of players having jersey number greater than 30.

SELECT TEAM_NAME, COUNT(PLAYER_ID) AS JERSEY_NO
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
WHERE PLAYER_JERSEY_NUMBER > 30
GROUP BY TEAM_NAME

--10. Display team name and total matches played by its players.

SELECT TEAM_NAME,PLAYER_FIRST_NAME, PLAYER_MATCHES_PLAYED
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
GROUP BY TEAM_NAME,PLAYER_FIRST_NAME, PLAYER_MATCHES_PLAYED


--Part –> B

--11. Display stadium city and total number of teams in each city.

SELECT STADIUM_CITY, TEAM_NAME
FROM STADIUM
INNER JOIN TEAM
ON STADIUM.STADIUM_ID = TEAM.HOME_STADIUM_ID
GROUP BY STADIUM_CITY,TEAM_NAME

--12. Display team name and average matches played by players in each team.

SELECT TEAM_NAME, AVG(PLAYER_MATCHES_PLAYED) AS AVERAGE_MATCHES
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
GROUP BY TEAM_NAME

--13. Display team name and maximum matches played by any player in each team.

SELECT TEAM_NAME, MAX(PLAYER_MATCHES_PLAYED) AS MAX_MATCHES
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
GROUP BY TEAM_NAME

--14. Display team name and minimum matches played by any player in each team.

SELECT TEAM_NAME, MIN(PLAYER_MATCHES_PLAYED) AS MIN_MATCHES
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
GROUP BY TEAM_NAME

--15. Display stadium name and total number of players playing under teams of that stadium.

SELECT STADIUM_NAME,COUNT(PLAYER_ID) AS NO_PLAYERS
FROM STADIUM
INNER JOIN TEAM
ON STADIUM.STADIUM_ID = TEAM.HOME_STADIUM_ID
INNER JOIN PLAYER
ON PLAYER.TEAM_ID = TEAM.TEAM_ID
GROUP BY STADIUM_NAME


--Part –> C

--16. Display teams having more all-rounders than bowlers.

SELECT TEAM_NAME
FROM TEAM
INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID


--17. Display teams where difference between max and min player matches is greater than 5.

--18. Display stadium city and total wins of teams in that city.

--19. Display team name and total number of players for each role (grouped by role).

--20. Display team name and total number of players whose name starts with ‘A’