--From the table PUBLISHER, AUTHOR and BOOK perform the following queries:

SELECT * FROM PUBLISHER
SELECT * FROM AUTHOR
SELECT * FROM BOOK

--Part –> A

--1. List all books with their authors.

SELECT * 
FROM BOOK INNER JOIN AUTHOR
ON BOOK.AUTHORID = AUTHOR.AUTHORID

--2. List all books with their publishers.

SELECT *
FROM BOOK INNER JOIN PUBLISHER
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID

--3. List all books with their authors and publishers.

SELECT *
FROM BOOK 
INNER JOIN PUBLISHER
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
INNER JOIN AUTHOR
ON AUTHOR.AUTHORID = BOOK.AUTHORID

--4. List all books published after 2010 with their authors and publisher and price.

SELECT TITLE,PUBLICATIONYEAR
FROM BOOK 
INNER JOIN AUTHOR
ON BOOK.AUTHORID = AUTHOR.AUTHORID
INNER JOIN PUBLISHER
ON PUBLISHER.PUBLISHERID = BOOK.PUBLISHERID
WHERE PUBLICATIONYEAR > 2010

--5. List all authors and the number of books they have written.

SELECT AUTHORNAME,COUNT(TITLE) AS NO_OF_BOOKS
FROM AUTHOR
INNER JOIN BOOK
ON AUTHOR.AUTHORID = BOOK.AUTHORID
GROUP BY AUTHORNAME

--6. List all publishers and the total price of books they have published.

SELECT PUBLISHERNAME, SUM(PRICE) AS TOTAL_PRICE
FROM PUBLISHER
INNER JOIN BOOK
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
GROUP BY PUBLISHERNAME

--7. List authors who have not written any books.

SELECT AUTHORNAME,BOOKID
FROM AUTHOR
LEFT JOIN BOOK
ON AUTHOR.AUTHORID = BOOK.AUTHORID
WHERE BOOKID IS NULL

--8. Display the total number of books written by each author along with the average price of their books.

SELECT AUTHORNAME,COUNT(TITLE) AS NO_OF_BOOKS,AVG(PRICE) AS AVERAGE_PRICE
FROM AUTHOR
INNER JOIN BOOK
ON AUTHOR.AUTHORID = BOOK.AUTHORID
GROUP BY AUTHORNAME 

--9. lists each publisher along with the total number of books they have published, sorted from highest to lowest.

SELECT PUBLISHERNAME,COUNT(TITLE) AS NO_OF_BOOKS
FROM PUBLISHER
INNER JOIN BOOK
ON PUBLISHER.PUBLISHERID = BOOK.PUBLISHERID
GROUP BY PUBLISHERNAME
ORDER BY COUNT(TITLE) DESC

--10. Display number of books published each year.

SELECT PUBLICATIONYEAR, COUNT(TITLE) AS NO_OF_BOOKS
FROM BOOK
INNER JOIN PUBLISHER
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
GROUP BY PUBLICATIONYEAR

--Part –> B

--11. List the publishers whose total book prices exceed 500, ordered by the total price.

SELECT PUBLISHERNAME, SUM(PRICE) AS TOTAL_PRICE
FROM PUBLISHER 
INNER JOIN BOOK
ON PUBLISHER.PUBLISHERID = BOOK.PUBLISHERID
GROUP BY PUBLISHERNAME
HAVING SUM(PRICE) > 500
ORDER BY SUM(PRICE)

--12. List most expensive book for each author, sort it with the highest price.

SELECT AUTHORNAME,SUM(PRICE) AS EXPENSIVE_BOOK
FROM BOOK
INNER JOIN AUTHOR
ON BOOK.AUTHORID = AUTHOR.AUTHORID
GROUP BY AUTHORNAME
ORDER BY SUM(PRICE) DESC

--13. Display publisher name and difference between maximum and minimum book price.

SELECT PUBLISHERNAME, MAX(PRICE) - MIN(PRICE) AS DIFFERENCE_IN_PRICE
FROM PUBLISHER
INNER JOIN BOOK
ON PUBLISHER.PUBLISHERID = BOOK.PUBLISHERID
GROUP BY PUBLISHERNAME

--14. List publisher name and total price of books published each year.

SELECT PUBLISHERNAME,PUBLICATIONYEAR,SUM(PRICE) AS TOTAL_PRICE
FROM PUBLISHER
INNER JOIN BOOK
ON PUBLISHER.PUBLISHERID = BOOK.PUBLISHERID
GROUP BY PUBLICATIONYEAR,PUBLISHERNAME

--15. Display author name and total price of books sorted by highest total price.

SELECT AUTHORNAME, SUM(PRICE) AS TOTAL_PRICE
FROM AUTHOR 
INNER JOIN BOOK
ON AUTHOR.AUTHORID = BOOK.AUTHORID
GROUP BY AUTHORNAME
ORDER BY SUM(PRICE) DESC


--TABLE EMPLYEE_MASTER
CREATE TABLE EMPLOYEE_MASTER
( EMPLOYEE_NO VARCHAR(30),
  NAME VARCHAR(30),
  MANAGER_NO VARCHAR(30))

INSERT INTO EMPLOYEE_MASTER
VALUES('E01','Tarun',NULL),
	  ('E02','Rohan','E02'),
	  ('E03','Priya','E01'),
	  ('E04','Milan','E03'),
	  ('E05','Jay','E01'),
	  ('E06','Anjana','E04')

SELECT * FROM EMPLOYEE_MASTER


--Part –> C

--16. Retrieve the names of employee along with their manager’s name from the Employee table.

SELECT E.NAME AS NAME, M.NAME AS MANAGER 
FROM EMPLOYEE_MASTER E
INNER JOIN EMPLOYEE_MASTER M
ON E.EMPLOYEE_NO = M.MANAGER_NO

--17. Display employees who are managers.

SELECT M.NAME AS MANAGER
FROM EMPLOYEE_MASTER E 
INNER JOIN EMPLOYEE_MASTER M
ON E.EMPLOYEE_NO = M.MANAGER_NO

--18. Display number of employees working under each manager.

SELECT E.NAME, COUNT(E.NAME) AS NO_OF_EMP
FROM EMPLOYEE_MASTER E
INNER JOIN EMPLOYEE_MASTER M
ON M.EMPLOYEE_NO = E.MANAGER_NO
GROUP BY E.NAME

--19. Display the employee’s name along with their manager’s name and senior manager name.

SELECT E.NAME AS EMP_NAME, M.NAME AS MANAGER_NAME 
FROM EMPLOYEE_MASTER E
INNER JOIN EMPLOYEE_MASTER M
ON M.EMPLOYEE_NO = E.MANAGER_NO

--20. Display managers and count of employees under them in descending order.

SELECT M.NAME AS MANAGER_NAME, COUNT(E.NAME) AS EMP_COUNT
FROM EMPLOYEE_MASTER E
INNER JOIN EMPLOYEE_MASTER M
ON M.EMPLOYEE_NO = E.MANAGER_NO
GROUP BY M.NAME
ORDER BY COUNT(E.NAME) DESC
