--From the table DEPARTMENT and PERSON perform the following queries:

--Part –> A

SELECT * FROM DEPARTMENT
SELECT * FROM PERSON

--1. Combine information from Person and Department table using cross join or Cartesian product.

SELECT *
FROM PERSON, DEPARTMENT

--2. Find all persons with their department name.

SELECT PERSONNAME,DEPARTMENTNAME
FROM PERSON LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--3. Find all persons with their department name & code.

SELECT PERSONNAME,DEPARTMENTNAME 
FROM PERSON LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--4. Find all persons with their department code and location.

SELECT PERSONNAME,DEPARTMENTCODE,LOCATION 
FROM PERSON LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID 

--5. Find the detail of the person who belongs to Mechanical department.

SELECT PERSONNAME,DEPARTMENTNAME
FROM PERSON RIGHT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENTNAME = 'MECHANICAL'

--6. Final person’s name, department code and salary who lives in Ahmedabad city.

SELECT PERSONNAME,DEPARTMENTCODE,SALARY
FROM PERSON RIGHT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE CITY = 'AHMEDABAD'

--7. Find the person's name whose department is in C-Block.

SELECT PERSONNAME,LOCATION
FROM PERSON INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE LOCATION = 'C-BLOCK' 

--8. Retrieve person name, salary & department name who belongs to Jamnagar city.

SELECT PERSONNAME,SALARY,DEPARTMENTNAME
FROM PERSON RIGHT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE CITY = 'JAMNAGAR'

--9. Retrieve person’s detail who joined the Civil department after 1-Aug-2001.

SELECT *
FROM PERSON INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENTNAME = 'CIVIL' AND JOININGDATE > '2001-08-01'

--10. Display all the person's name with the department whose joining date difference with the current date is more than 25 years.

SELECT PERSONNAME,DEPARTMENTNAME
FROM PERSON INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DATEDIFF(DAY,JOININGDATE, GETDATE()) > 25

--11. Find department wise person counts.

SELECT DEPARTMENTNAME,COUNT(PERSON.PERSONID) AS COUNT_PERSON
FROM PERSON INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENTNAME

--12. Give department wise maximum & minimum salary with department name.

SELECT DEPARTMENTNAME, MIN(SALARY) AS MIN_SALARY, MAX(SALARY) AS MAX_SALARY
FROM PERSON INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME

--13. Find city wise total, average, maximum and minimum salary.

SELECT CITY, SUM(SALARY) AS TOTAL_SALARY,AVG(SALARY) AS AVG_SALARY,MAX(SALARY) AS MAX_SALARY,MIN(SALARY) AS MIN_SALARY
FROM PERSON INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY CITY

--14. Find the average salary of a person who belongs to Ahmedabad city.

SELECT CITY,AVG(SALARY)
FROM PERSON LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE CITY = 'AHMEDABAD'
GROUP BY CITY

--15. Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In single column)

SELECT PERSONNAME + 'LIVES IN' + CITY + 'WORKS IN' + DEPARTMENTNAME
FROM PERSON INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID


--Part –> B

--16. Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In single column)

SELECT PERSONNAME + 'EARNS' + CAST(SALARY AS VARCHAR(20)) + 'FROM' + DEPARTMENTNAME + 'DEPARTMENT MONTHLY'
FROM PERSON INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--17. Find city & department wise total, average & maximum salaries.

SELECT CITY,DEPARTMENTNAME,SUM(SALARY) AS TOTAL_SALARY,AVG(SALARY) AS AVG_SALARY,MAX(SALARY) AS MAX_SALARY
FROM PERSON INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY CITY, DEPARTMENTNAME

--18. Find all persons who do not belong to any department.

SELECT PERSONNAME,DEPARTMENTNAME
FROM PERSON LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENTNAME IS NULL

--19. Find all departments whose total salary is exceeding 100000.

SELECT DEPARTMENTNAME,SUM(SALARY)
FROM PERSON INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING SUM(SALARY) > 100000


--Part – C:

--20. List all departments who have no person.

SELECT DEPARTMENTNAME
FROM PERSON LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE PERSONNAME IS NULL

--21. List out department names in which more than two persons are working.

SELECT DEPARTMENTNAME,COUNT(DEPARTMENT.DEPARTMENTID) AS COUNT_PERSON
FROM PERSON RIGHT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING COUNT(DEPARTMENT.DEPARTMENTID) > 2

--22. Give a 10% increment in the computer department employee’s salary. (Use Update)

UPDATE PERSON
SET SALARY = SALARY*0.1
FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENTNAME = 'COMPUTER'